#!/usr/bin/python3
# -*- coding:utf-8 -*-
def zh_cn():
    return {"app_name":"PYCommandLineTranslators",
            "gui_about":"E-mail : zsh2401@163.com\n捐赠 : 支付宝 zsh2401@163.com\n",
            "gui_about_version":"版本: 0.7.0",
            "open_source":"将会调用系统浏览器打开一个网页,如果没有,请自行访问开源地址:github.com/zsh2401/PYCLT\n开源协议:GPL3.0",
            "about":"开发者信息",
            "windowsPS":"检测到您是windows系统\n上面的颜色符号可能出现了乱码?\n如果是的,建议您使用powershell或gui版PYCLT,命令cltn",
            "donate":"捐赠!",
            "about_version":"版本",
            "about_open_source":"开源相关",
            "version":"0.7.0",
            "query":"原词",
            "messagebox_title":"PYCLT",
            "translation":"主要释义",
            "result_from_netease":"主要内容",
            "phonetic":"发音",
            "uk-phonetic":"英式发音",
            "us-phonetic":"美式发音",
            "explains":"主要释义",
            "more_ex":"主要英文释义",
            "result_from_web":"短语",
            "xingtai":"形态",
            "word_pl":"复数形式",
            "word_past":"过去形式",
            "word_done":"完成形态",
            "word_ing":"现在进行时",
            "word_third":"第三人称",
            "word_er":"比较级",
            "word_est":"最高级",
            "can_use_clts":"为了提高效率,请使用cltn命令 如  cltn fuck",
            "more_api_use":"你也可以使用\ncltb\t使用百度api\ncltj\t使用金山api",
            "one_more_time":"one_more_chance",
            "header":"CommandLine",
            "thanks":"Netease Api",
            "api_not_enable":"此API暂未开放,请等待版本更新...",
            "please_input":"请输入点东西!",
            "tans":"点击进行翻译",
            "clear":"清屏",
            "tk_error":"tkinter出现的错误!无法启动GUI版程序,您可以尝试cltj <text> 来进行翻译",
            "loading":"加载结果中...请稍等...可能会未响应....",
            "loading_netease":"正在加载网易有道翻译API",
            'loaded_netease':"网易有道翻译API加载完成",
            "loading_jinshan":"正在加载金山翻译API",
            "loaded_jinshan":"金山翻译API加载完成",
            "loading_baidu":"正在加载百度翻译API",
            "loaded_baidu":"百度翻译API加载完成",
            "loading_netease_spider":"正在加载网易有道翻译爬虫API",
            "loaded_netease_spider":"网易有道翻译爬虫API加载完成",
            "devel":"开发者",
            "dever":"zsh2401@163.com",
            "simple_header":"使用爬虫翻译器,因此获得结果将比较简单",
            "more_arg":"检测到传入了多个参数!您是想翻译多个短语吗?\n翻译短语示例(重点在引号上!): pyclt 'where am i'",
            "SomeError":"发生了某个严重的错误,请稍候再试试?你可以试试别的API??",
            "CreateDataFolder":"创建数据文件",
            "error_notice":"API发生了错误,可以尝试使用clts -s TEXT 进行翻译",
            "code_20":"要翻译的文本过长",
            "code_30":"无法进行有效的翻译",
            "code_40":"不支持的语言类型",
            "code_50":"无效的key",
            "code_60":"无词典结果，仅在获取词典结果生效"
            }
def en_us():
    return {"app_name":"CommandLineTranslators",
            "version":"0.5",
            "query":"Query",
            "translation":"Translation",
            "result_from_netease":"Explain",
            "phonetic":"Phonetic",
            "uk-phonetic":"Phonetic-UK",
            "us-phonetic":"Phonetic-US",
            "explains":"Explains",
            "result_from_web":"Short Cut",
            "one_more_time":"one_more_chance",
            "SomeError":"ERROR",
            "code_20":"long text",
            "code_30":"failed",
            "code_40":"no this lang",
            "code_50":"key error",
            "code_60":"no dict"
            }
